2 api documentation architecture presentation anik
beyond-the-seas-org/Planning-Presentations pull request #3
Opened 2023-07-09 20:06 UTC by ANIK115

Please review the api_doc.md file and merge with yours @asifhaider

2023-07-09 22:48 UTC, asifhaider requested changes
Take a look at the review comments. I have tried to point out the potential bugs and inconsistencies in the API design. We will merge both of our API docs in one file once you sort these issues out. Thanks.

2023-07-09 22:48 UTC, asifhaider commented on api_doc.md
> +| [beyond-the-seas.org/api/newsfeed/add-post](beyond-the-seas.org/api/newsfeed/add-post) | POST | {<br> &ensp; "user_id": 1,<br> &ensp; "user_name": "Azizur Rahman",<br> &ensp; "description": "post 1
I don't think we need 'user_name' even after specifying the 'user_id' in HTTP request, as user_id should be able to uniquely define the user who is going to add a post. What do you think about it?

2023-07-09 22:48 UTC, asifhaider commented on api_doc.md
> +| [beyond-the-seas.org/api/newsfeed/{user_id}/{post_id}/{comment_id}/delete](beyond-the-seas.org/api/newsfeed/{user_id}/{post_id}/{comment_id}/delete) | POST | {<br> &ensp; "user_id": 1,<br> &ensp; "
I think we should use 'DELETE' type instead of 'POST' type here. Check it please.

2023-07-09 22:48 UTC, asifhaider commented on api_doc.md
> +| [beyond-the-seas.org/api/newsfeed/feed?start=0&count=4](beyond-the-seas.org/api/newsfeed/feed?start=0&count=4)                                                           | GET        | {}
'newsfeed/posts?...' looks better than 'newsfeed/feed...'

2023-07-09 22:48 UTC, asifhaider commented on api_doc.md
> +| `GET` Community Newsfeed |
'newsfeed/feed?...' can be replaced by 'newsfeed/posts?...'

2023-07-09 22:48 UTC, asifhaider commented on api_doc.md
> +| [beyond-the-seas.org/api/community/create](beyond-the-seas.org/api/community/create) | POST | {<br> &ensp; "user_id": 1,<br> &ensp; "community_name": "Bangladesh",<br> &ensp; "community_description
Community name and Country name exactly same, can be changed like 'Bangladeshi Students' Group'.

2023-07-09 22:48 UTC, asifhaider commented on api_doc.md
> +| [beyond-the-seas.org/api/analytics/preference-analysis](beyond-the-seas.org/api/analytics/preference-analysis) | GET | {<br>"user_id":1, <br>"newsfeed_analytics":{}, <br> "community_analytics":{},
Not sure why we passed 'user_id' here to retrieve analytics results. Because the URL/ API endpoint doesn't need user_id to proceed. Check this, maybe?

2023-07-10 00:23 UTC, ANIK115 commented on api_doc.md
> +| [beyond-the-seas.org/api/newsfeed/{user_id}/{post_id}/{comment_id}/delete](beyond-the-seas.org/api/newsfeed/{user_id}/{post_id}/{comment_id}/delete) | POST | {<br> &ensp; "user_id": 1,<br> &ensp; "
Okay, correcting it.

2023-07-10 00:29 UTC, ANIK115 commented on api_doc.md
> +| [beyond-the-seas.org/api/newsfeed/feed?start=0&count=4](beyond-the-seas.org/api/newsfeed/feed?start=0&count=4)                                                           | GET        | {}
Replaced with posts

2023-07-10 00:29 UTC, ANIK115 commented on api_doc.md
> +| `GET` Community Newsfeed |
replaced with posts

2023-07-10 00:31 UTC, ANIK115 commented on api_doc.md
> +| [beyond-the-seas.org/api/community/create](beyond-the-seas.org/api/community/create) | POST | {<br> &ensp; "user_id": 1,<br> &ensp; "community_name": "Bangladesh",<br> &ensp; "community_description
changed with "Florida Bangladeshi Community" according to our mock ui

2023-07-10 00:34 UTC, ANIK115 commented on api_doc.md
> +| [beyond-the-seas.org/api/analytics/preference-analysis](beyond-the-seas.org/api/analytics/preference-analysis) | GET | {<br>"user_id":1, <br>"newsfeed_analytics":{}, <br> "community_analytics":{},
When this api is called, it will call some other apis for collecting user profile analytics, newsfeed analytics etc. we need the user_id to call "beyond-the-seas.org/api/analytics/user-profile" this api internally

2023-07-10 00:44 UTC, asifhaider approved these changes
Looks good now

2023-07-10 00:46 UTC, asifhaider commented on api_doc.md
> +| [beyond-the-seas.org/api/analytics/preference-analysis](beyond-the-seas.org/api/analytics/preference-analysis) | GET | {<br>"user_id":1, <br>"newsfeed_analytics":{}, <br> "community_analytics":{},
Got it

2023-07-10 00:47 UTC, merged